# _config.yml

# Site settings
title: My Awesome Site
description: A comprehensive web crawler project hosted on GitHub Pages. Explore crawled data and insights from various websites!
url: https://yourusername.github.io/your-repo-name  # Replace with your GitHub Pages URL

# Author settings
author:
  name: jesse winghart
  email: https://formsubmit.co/el/sumuhu 

# Social media links
social:
 # twitter: https://twitter.com/yourprofile
 # github: https://github.com/yourusername
 # linkedin: https://linkedin.com/in/yourprofile

# Build settings
theme: minima  # Change to your preferred theme
plugins:
  - jekyll-feed  # Generates an Atom feed for your site
  - jekyll-seo-tag  # Adds SEO tags to your site

# Navigation settings
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Crawl Results
    url: /results/

# Permalinks settings
permalinks:
  pretty: /:title/

# Exclude files from the build
exclude:
  - README.md
  - LICENSE
  - CONTRIBUTING.md

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown

# SEO settings
seo:
  enable: true  # Enable SEO features
  meta_description: "Explore the capabilities of our advanced web crawler, designed to automate the process of extracting data from websites. This project showcases dynamic data retrieval, link analysis, and user-friendly visualization of crawled results. Ideal for developers, researchers, and data enthusiasts looking to enhance their web scraping skills. Hosted on GitHub Pages, it provides a seamless experience with easily accessible data in both JSON and CSV formats."
  keywords: web crawler, GitHub Pages, data visualization, project showcase

# Custom settings
custom:
  feature_flag: true  # Custom feature toggles

# Google Analytics
google_analytics: UA-XXXXXXXXX-X  # Replace with your Google Analytics tracking ID

# Deployment settings
# Uncomment the following line if you want to automatically deploy to GitHub Pages
 auto_deploy: true

# Additional settings can be added here as needed
