name: Deployment and Actions Counter

on:
  issues:
    types: [opened]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  count-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup data directory
        run: mkdir -p data

      - name: Fetch deployment count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deployments_count=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/unaveragetech/PagesXcrawler/deployments" | jq 'length')
          echo '{"schemaVersion": 1, "label": "Deployments", "message": "'"$deployments_count"'", "color": "blue"}' > data/deployments.json

      - name: Fetch workflow run count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          actions_count=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/unaveragetech/PagesXcrawler/actions/runs" | jq '.total_count')
          echo '{"schemaVersion": 1, "label": "Actions", "message": "'"$actions_count"'", "color": "green"}' > data/actions.json

      - name: Commit updated counters
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions Bot"
          git add data/deployments.json data/actions.json
          git commit -m "Update counters for deployments and actions"
          git push
