name: Log Issue Status

on:
  workflow_run:
    workflows: ["Web Crawler"]  # Name of the original workflow
    types:
      - completed

jobs:
  log_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Log issue status
        run: |
          CSV_FILE="data/issues_status.csv"

          # Check if the CSV file exists, create if not
          if [ ! -f "$CSV_FILE" ]; then
              echo "Issue,Status" > "$CSV_FILE"
          fi

          # Get the issue title from the previous workflow
          issue_title="${{ github.event.workflow_run.head_commit.message }}"  # Adjust if necessary
          
          # Log the completed issue
          echo "$issue_title,Completed" >> "$CSV_FILE"

      - name: Close the issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER="${{ github.event.workflow_run.head_commit.id }}"  # Extract the issue number
          echo "Closing issue #$ISSUE_NUMBER"
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER \
            -d '{"state": "closed"}'
